### ISSUE TITLE
Try Physics-based Animations

### ISSUE THREAD

**Issue by YoshihideSogawa** [recruit-lifestyle/FloatingView#44]
What is the [Physics-based Animations](https://developer.android.com/topic/libraries/support-library/preview/physics-based-animation.html)
To solve #19

**Comment by geecko86** [comment]
I was about to start playing with this, but it looks like this Physics-based support lib has **API 16** as their MinSDK.

Should I give up or does that pose no problem?

API 14 and 15 have ridiculously low market share.
https://developer.android.com/about/dashboards/index.html

**Comment by YoshihideSogawa** [comment]
Thank you for your information.
The feature is not incorporated immediately.
I want to develop it while exchanging information with everyone.

**Comment by geecko86** [comment]
I'm really sorry but.. Your English is not the best and I can't say I'm sure I understand.
You mean to say it's not a priority and you still need to investigate?
In any case, I'd like to work on it because my app will make use of this library and I think it needs feature.

I've been working on it for the past few hours and I've been facing an issue where a **VelocityTracker** gives me some wrong velocity data when flinging the FloatingView. (The Physics library uses the initial velocity to compute the SpringAnimation or FlingAnimation)

I.e. I'm flinging the view so that it moves to the top of the screen and the velocitytracker will sometimes tell me I moved it in the opposite direction. This leads to very random movement in the app.

[This comment on StackOverflow](https://stackoverflow.com/questions/40380349/android-velocity-tracker-giving-wrong-values-of-velocity#comment68021153_40380349) seems to say that calling WindowManager.updateViewLayout messes with the VelocityTracker.

**Comment by geecko86** [comment]
You can check out what I mean on my repository:
https://github.com/geecko86/FloatingView

**Comment by YoshihideSogawa** [comment]
I am faced with this problem too.
I'm continuing to investigate to solve it.
https://stackoverflow.com/questions/44825129/velocitytracker-gives-me-wrong-velocity-because-of-updateviewlayout

**Comment by YoshihideSogawa** [comment]
Sorry for being late.
Support [Ver 2.3.0](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.3.0)
